
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist_authentication?useSSL=false
    username: root
    password: root


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
